### ISSUE TITLE
Update to 1.28?

### ISSUE THREAD

**Issue by shockingfargroundx** [kinsi55/BeatSaber_Shaffuru#13]
Can you make an update to the mod that works with 1.28 please?

**Comment by kinsi55** [comment]
I suppose you mean to 1.28.1 (The Alpha), in which case the answer is, yes at some point. Its at least a month until that version gets released

**Comment by shockingfargroundx** [comment]
Can you maybe do 1.27 as well sometime down the road? (Sorry for asking too much)

**Comment by kinsi55** [comment]
The latest release should work just fine on 1.27

**Comment by shockingfargroundx** [comment]
> The latest release should work just fine on 1.27 does it not?

I seem to have issues of it not showing up on my mods tab

**Comment by kinsi55** [comment]
At least for 1.27 it does show up just fine for me (I cannot actually press the start button, but it does show up) so I reckon you have some different issue or missing dependency.

**Comment by kinsi55** [comment]
I actually just tested it on 1.28 and that also works - Can you attach a game log?

**Comment by shockingfargroundx** [comment]
I just checked the Requirements. I was missing SongDetailsCache I don't know why I was but I was. Thanks for the help!
